language: elixir
elixir:
  - "1.10"
otp_release:
  - 23.0
env:
  - PORT=3000
script:
  - "MIX_ENV=test mix do compile, coveralls.json --umbrella"

after_success:
  - bash <(curl -s https://codecov.io/bash)
